# Use Node.js 16 Alpine image
FROM node:16-alpine

# Set work directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project
COPY . .

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]